.circleci/config.yml

Mostly the basic setup here. We'll get a little more advanced shortly.

set up CI for bookstore

---

.circleci/config.yml
bookstore/__init__.py
bookstore/archive.py
bookstore/handlers.py
bookstore/jupyter_server_extension/__init__.py
ci/integration.js
ci/jupyter.js
ci/jupyter_notebook_config.py
ci/s3.js
ci/sleep.js
ci/token.js
package.json
requirements.txt

set up minio on circle

---

.circleci/config.yml

Little bits to add on from #11

Cleanup circle

---

bookstore/archive.py

Deleted unused imports and ran `black` on the code.
cc @willingc

clean up unused imports and blacken

---

bookstore/__init__.py
bookstore/_version.py
bookstore/archive.py
bookstore/bookstore_config.py
bookstore/handlers.py
docs/source/conf.py
versioneer.py

To make the changes in #20 smaller, I've run `black` over all the python source.
xref: #19

run black over everything

---

.circleci/config.yml
bookstore/archive.py
bookstore/bookstore_config.py
bookstore/handlers.py

Perform S3 Writes on Threads

---

.circleci/config.yml
.gitignore
README.md
bookstore/handlers.py
ci/integration.js
ci/jupyter.js

This adds functionality for publishing Notebooks to ci-published and then to compare what is stored there against our in memory copy.
Also adds an integration test for that functionality.

Publish integration

---

CHANGELOG.md
CHECKLIST-release.md
RELEASING.md
docs/source/changelog.rst
docs/source/code_of_conduct.rst
docs/source/contributing.rst
docs/source/index.rst
docs/source/releasing.rst

- adds releasing checklist and instructions
- add project docs from root directory (CoC, Change Log, etc) to Sphinx docs

Add releasing checklist and project docs

---

.circleci/config.yml
.travis.yml

- correct circle ci fail after merge https://circleci.com/gh/nteract/bookstore/156

remove the editable install

---

bookstore/client/notebook.py

- creates reusable requests.Sessions object and prepopulates it with headers
- headers include: xsrf_token, Authorization token, Content-type as application/json
- pulls in xsrf token from login page
- creates self.sessions property that makes request each time since it can change

General client improvements (auth, sessions, &c.)

---

CHANGELOG.md
CONTRIBUTING.md
running_ci_locally.md

Minor edits to docs from review.
- Partially closes #86

Address doc review feedback from PR #75

---

docs/source/usage.rst

- Make the doc more user focused
- Add a bit more text for understanding
- Image can be replaced at a later date.

Edit usage documentation

---

ci/jupyter.js
ci/utils.js

- Addresses feedback on #75 
- Partially closes #86

Add PR #75 review feedback for js from @stormpython @captainsafia

---

ci/utils.js

This pulls out the fix in #106 to fix CI testing for now while the POST stuff is still in the works.

Fix bug in trying to redefine const, switch to let

---

README.md
docs/source/project/index.rst
docs/source/project/python_tests.rst
requirements-dev.txt
running_python_tests.md
setup.py
tox.ini

Settings shamelessly taken from papermill.

Add tox file

---

.coveragerc
.travis.yml
MANIFEST.in
README.md
pytest.ini
running_python_tests.md
tox.ini

Closes #116 #112 
- update tox.ini for black and mypy
- add tox to travis config

Configure travis to use tox

---

bookstore/__init__.py
bookstore/client/nb_client.py
bookstore/client/store_client.py
bookstore/clone.py
bookstore/publish.py
ci/clone_request.py
ci/utils.js

- Addresses #75 feedback for Python files
- Partially closes #86

Add PR #75 review feedback for python files from @MSeal and @willingc

---

bookstore/client/nb_client.py

Remove TODO and add docstring

---

docs/source/reference/store_client.rst

This addresses the "broken" part of #122.

store_client rst header fix

---

.readthedocs.yml
docs/requirements-doc.txt
setup.py

Addresses #122 
[Test build](https://test-bookstore.readthedocs.io/en/dociss/reference/archive.html#module-bookstore.archive)

Fix autodoc on rtd

---

docs/source/index.rst
docs/source/reference/archive.rst
docs/source/reference/bookstore_config.rst
docs/source/reference/clone.rst
docs/source/reference/handlers.rst
docs/source/reference/index.rst
docs/source/reference/nb_client.rst
docs/source/reference/publish.rst
docs/source/reference/s3_paths.rst
docs/source/reference/store_client.rst
tox.ini

Addresses #122 
Adds headings and subheadings

Reformat autodoc reference pages

---

bookstore/tests/test_utils.py

Addresses #118 
We could parameterize the last test at some point. For now, I am leaving as is.

Add tests for utils

---

bookstore/tests/test_archive.py
bookstore/tests/test_publish.py
pytest.ini
requirements-dev.txt
setup.py
tox.ini

There's still work to do with the async tests. I don't plan to add to this PR so please review as is.

Add test stubs for archive and publish

---

bookstore/bookstore_config.py

Change `Int` to the preferred `Integer`. [Traitlets doc](https://traitlets.readthedocs.io/en/stable/trait_types.html#traitlets.Long)

Use preferred form of traitlets integer

---

bookstore/publish.py
docs/source/reference/publish.rst

This adds docstrings and changes which methods will be auto-doc'd.

Quick fixes docs for publish docs 

---

bookstore/client/nb_client.py
bookstore/client/store_client.py

As I was writing up the changelog, I realised we should be highlighting that in comparison to the rest of the library, these are experimental features that are not as well tested. 
For instance, I realized that the current endpoints for bookstore did not match those that we actually provide as part of our API 🤦‍♀.
The changes to the endpoints are the only non-doc changes. If needed to get this ready to be merged in time for 2.3.0, I can break those out into a separate PR before we release: https://github.com/nteract/bookstore/pull/142/commits/80a9559f5a0d50175919f0dfda74dcdfa116d5bb
So I fixed that, and updated all of their docstrings to mention their experimental nature. I didn't do so for the records because we're actually testing those. 
While I was at it I also improved the docstrings …

Fixes client endpoints and adds docstrings

---

CHANGELOG.md

This could probably use some word-smithing. But here's a first pass at the changelog.
I focused on significant changes rather than cataloguing the different PRs. If we want to I can link the PRs from their relevant areas of focus.

First draft of changelog for 2.3.0; focuses on significant changes

---

bookstore/clone.html

S3 gives a 200 not a 201 response, so we need to update the html template to reflect that.

Update status code to reflect response from S3 on success (200 not 201)

---

bookstore/bookstore_config.py
bookstore/handlers.py
bookstore/tests/test_bookstore_config.py
bookstore/tests/test_handlers.py
docs/source/bookstore_api.yaml

This addresses the first piece of the #154 plan, setting up the configuration and validation.

Fs cloning traitlet

---

bookstore/clone.py
bookstore/tests/test_clone.py
docs/source/reference/clone.rst

This adds a GET handler for file-system cloning.
Requires #157.

Fs cloning handler

---

bookstore/bookstore_config.py
bookstore/clone.py
bookstore/handlers.py
bookstore/tests/test_bookstore_config.py
bookstore/tests/test_clone.py
bookstore/tests/test_handlers.py

Builds on #158, adding the route to the server so this can be tested directly.

End to End testing Cloning Landing page

---

CHANGELOG.md

This updates the changelog for 2.4.0, preparing us for a release later today.

Add Changelog for 2.4.0
