nteract/bookstore

bookstore/__init__.py
bookstore/archive.py
bookstore/jupyter_server_extension/__init__.py
bookstore/jupyter_server_extension/handlers.py

Sets up bookstore as a jupyter extension. This will be used for new API endpoints as we need them for publishing, scheduling, and if we end up needing them for versioning.

setup the very basics of a jupyter extension

---

README.md
bookstore/__init__.py
bookstore/archive.py
bookstore/bookstore_config.py
jupyter_notebook_config.py.example
requirements.txt

This sets up our configuration to be one `BookstoreSettings` class that gets used by the `BookstoreContentsArchiver` and will get used by the publish & schedule handlers.

setup config for use in archiver

---

running_ci_locally.md

This follows up on a note in https://github.com/nteract/bookstore/pull/28.
This adds instructions on how to make a local ci setup work. This was necessary for finding the tornado event loop issue described in #28.

Add docs about how to run the ci tests locally

---

requirements.txt

I was attempting to run the integration tests on master locally(more on that in a separate PR) and was running into issues with how `Future`s were being processed by the event loop. 
[I 17:45:05.385 NotebookApp] Processing storage write of ci-local-writeout2.ipynb
[E 17:45:05.387 NotebookApp] Error while archiving file: ci-local-writeout2.ipynb object Future can't be used in 'await' expression
Traceback (most recent call last):
File "/Users/mpacer/jupyter/bookstore/bookstore/archive.py", line 70, in archive
await self.write_to_s3(full_path, record.content)
TypeError: object Future can't be used in 'await' expression
After investigating https://stackoverflow.com/questions/34376814/await-future-from-executor-future-cant-be-used-in-await-expression and looking at …

Add tornado requirement to address event loop issues

---

ci/integration.js

Without this sleep on my local machine when running the ci
I would run into an error where by the time it was checking
for ci-local-writeout2.ipynb it had save: 2 not save: 3
according to minio.
Here is what the end of the error looked like: 
```
ci-local-writeout2.ipynb
{"cells": [], "nbformat": 4, "nbformat_minor": 2, "metadata": {"save": 2}}
original
{ cells: [],
nbformat: 4,
nbformat_minor: 2,
metadata: { save: 3 } }
from s3
{ cells: [],
nbformat: 4,
nbformat_minor: 2,
metadata: { save: 2 } }
unhandledRejection Error: Notebook on S3 does not match what we sent
at compareNotebooks (/Users/mpacer/jupyter/bookstore/ci/integration.js:82:13)
at <anonymous>
at process._tickCallback (internal/process/next_tick.js:182:7)
Error: Notebook on S3 does not match what we sent
at compareNotebooks …
```

Add sleep to loop for minio and jupyter to talk

---

bookstore/archive.py
bookstore/s3_paths.py
requirements.txt

It is remarkable how much nicer & cleaner this API is.
client.put_object seems to expect/allow json content encoded as a `str` (rather than requiring us to reëncode of json content back to `bytes`). I'm not sure if that's a good thing or a bad thing, but if it's a bad thing we need to probably update our tests to capture the case where that causes a problem.

refactors archive functionality to use aiobotocore & asyncio

---

.circleci/config.yml
jupyter_config/jupyter_notebook_config.d/bookstore.json
setup.py

add data_files to setup.py so it automatically enables serverextension
also: cleans up setup.py os.path imports

Automatically enable serverextension if one is not using an editable install

---

bookstore/bookstore_config.py
bookstore/tests/test_bookstore_config.py

@rgbkrkr asked to have a way to test for whether bookstore is properly configured over in the nteract_on_jupyter handler.
I felt like the business logic for that should live in the bookstore repo… seemed like the best way to do that would be to expose a validation function.
Since it requires that a collection of values are set appropriately, I figured it was going to be more straightforward to write a quick function rather than define custom validation functions for each one of the traitlets in question.
In the long run, we might want to go in the traitlets direction… but, for now, this seemed like a good way to delay validation and expose it to another library.

add simple validate_bookstore function & tests (not traitlets validate)

---

bookstore/bookstore_config.py
bookstore/handlers.py
bookstore/tests/test_bookstore_config.py
ci/jupyter.js

This does a little bit of a few things:
- makes it so settings don't validate by default (you need to know what your s3_bucket is even if you are using IAM roles)
- switch to using initialize rather than __init__ for the handler
- adds validation info onto base `api/bookstore/` endpoint
- changes logging level for testing so we see more info about the server

Cleanup settings validation

---

README.md

Only the jupyter server that bookstore would be attached to has to run Python 3.6+

Wordsmith our Python 3.6 requirement

---

CONTRIBUTING.md
bookstore/archive.py
docs/source/changelog.rst
docs/source/code_of_conduct.rst
docs/source/conf.py
docs/source/configuration.rst
docs/source/contributing.rst
docs/source/index.rst
docs/source/installation.rst
docs/source/project/changelog.rst
docs/source/project/code_of_conduct.rst
docs/source/project/contributing.rst
docs/source/project/index.rst
docs/source/project/releasing.rst
docs/source/reference/archive.rst
docs/source/reference/bookstore.rst
docs/source/reference/bookstore_config.rst
docs/source/reference/handlers.rst
docs/source/reference/modules.rst
docs/source/reference/s3_paths.rst
docs/source/releasing.rst
docs/source/usage.rst

- edits `archive.py` docstrings
- proposes changing `ability_to_create_path_lock` to `path_lock_ready`
- Autodoc all source files for Sphinx 
[Rendered docs](https://test-bookstore.readthedocs.io/en/archive-update/index.html)

Add detail to archive docstrings and Sphinx docs

---

readthedocs.yml
requirements.txt
setup.py

- Adds the [aioboto3](https://pypi.org/project/aioboto3/) package which when installed after aiobotocore resolves the boto3 dependency conflict since aioboto3 is a wrapper around boto3 and aiobotocore
- Build docs from latest RTD image so we can use Python 3.6

Add aioboto3 dependency and float up aiobotocore

---

bookstore/bookstore_config.py
bookstore/handlers.py
bookstore/tests/test_bookstore_config.py

Per conversation with @stormpython about feature specific config and settling on an API as soon as possible, this switches over the current validation code over to returning a dict (object once converted to json).
- "bookstore_validation" Checks whether bookstore overall has been 
validated (is false by default unless you set a s3_bucket)
- "archive_validation" Checks whether archiving has been configured
- "published_validation" Checks whether publishing has been configured

change API for validation to return an dict with feature specific checks

---

bookstore/handlers.py

This is a further iteration on how we will surface the settings via api and via the webapp settings for use by other serverextensions.

switches from storing the validation to storing bookstore settings

---

bookstore/clone.html
bookstore/clone.py
bookstore/handlers.py
bookstore/publish.py
bookstore/utils.py

Currently, the clone landing page from the GET api does not properly resolve base_urls. This addresses it. 
As it relates to https://github.com/nteract/bookstore/pull/75#discussion_r280785802 and the todo in https://github.com/nteract/bookstore/pull/88:
This is a case where because we lac a `url_path_join` utility in the front-end, it is easier to rely on the one provided by the notebook package from the backend rather than doing the text parsing for ourselves.
For example, working with `base_url`s causes a lot of headaches.
```
ipdb> self.default_url
'/blah/tree'
ipdb> self.base_url
'/blah/'
```
@willingc given your experience from JupyterHub & it's routing & base_url paradigms is there a better way to get access to the host name & protocol than to pull it from the request?

Address base_urls properly; handle path creation on the back end

---

bookstore/bookstore_api.yaml

I didn't include anything about the `ArchiveContentsManager`, because it doesn't really have an API in the sense of the handlers.
This should address one of #96's points.

Draft api docs

---

bookstore/clone.py
bookstore/tests/test_clone.py

This adds testing functionality and mocking for the clone handler's GET methods. 
This mostly was focused on figuring out how to mock up most of what we need to test the handler without actually requiring a running server. 
This also factors out the parameterization for the template so that we can test that separately. 
To get the POST tested will require adding moto (to mock up s3 and interactions with `aiobotocore`).
Many thanks to @mseal for help getting the initial framework up and running.

Clone GET Testing

---

bookstore/client/__init__.py
bookstore/clone.py
bookstore/handlers.py
bookstore/publish.py
bookstore/tests/test_clone.py
ci/integration.js
ci/jupyter.js
docs/source/bookstore_api.yaml

Closes #109 
This does not address the switch in all of the APIs as well, I will add that to this PR as it seems thematically related enough to go with it (and it would run into merge conflicts with this if I were to make it an independent PR).
This introduces BookstoreCloneAPIHandler, that inherits from APIHandler rather than IPythonHandler.

Refactor Clone handler

---

bookstore/clone.py
bookstore/tests/test_clone.py

This continues #102 to add more testing for the post handler.
I have not yet gotten the mock to work correctly to test the newly introduced helper function.
This also adds a quick fix to the js files that had broken the CI tests when run locally. It's concerning to me that that didn't come up in our CI testing, since updating a const should always cause an issue which suggests the tests weren't being run

Add POST handler tests for cloning

---

bookstore/bookstore_config.py
bookstore/handlers.py
bookstore/tests/test_bookstore_config.py
bookstore/tests/test_handlers.py
requirements-dev.txt

The biggest win in this is that this tests which endpoints & handlers are actually enabled in the handlers module. #130 does not address this, and should probably be rebased on top of this if this is merged.
- adds a way to disable cloning via `BookstoreSettings.cloning_enabled` traitlet
- adds `cloning_enabled` to validation code
- adds a new `build_handlers` function so we can test it directly (allowing less mocking)
- changes the semantics of `publish_enabled` and `archive_enabled`
- updates our `pytest` requirement to include `pytest>=3.6` (as required by `pytest-asyncio` as reported in [this issue](pytest-dev/pytest-asyncio#115))

Refactor & Test Validation and Handler Adding

---

bookstore/clone.py
bookstore/handlers.py
bookstore/publish.py
bookstore/tests/test_handlers.py
bookstore/tests/test_publish.py
docs/source/bookstore_api.yaml
docs/source/reference/publish.rst

This PR grew a bit, however the core of it is the creation of new publish handler tests.
It also refactors some of the code so it is more encapsulated and testable.
Because I realized as I was going through the tests that we weren't doing a great job of catching invalid request bodies, It also adds better validation around those.
That then led to a realization that our API docs were not appropriately specific about the request body.
Specifically, it said it needed to be a Contents API compatible message, but that wasn't the case. Furthermore, that behaviour doesn't match the APIs expected in the current notebook's contents handlers.

Publish test

---

bookstore/archive.py
bookstore/tests/test_archive.py

From my perspective, the most important thing this PR does is to add a test to ensure that we test the code path where we skip archiving based on a lock having been already acquired.

Archive test improvements

---

bookstore/clone.py
bookstore/tests/test_clone.py
docs/source/reference/clone.rst

I wanted to set us up for success going forward around cloning.  
The difficulty we were having getting coverage in the tests suggested to me that we hadn't properly isolated the different pieces of the logic. When I started diving in it became clear that the internal logic of the clone API handler could use a lot of attention & refactoring.
Once the refactor was done it was fairly straightforward to test. 
Also made general improvements
- Docstring improvements
- Distinguish between notebooks and files (previously we were treating all types of content identically)
- we weren't returning the s3 relevant info we were recording (which means changing the response API
Overall the code should be much easier to follow.

Clone Refactor & Test improvements

---

bookstore/bookstore_config.py
bookstore/handlers.py
bookstore/tests/test_bookstore_config.py
bookstore/tests/test_handlers.py
docs/source/bookstore_api.yaml

This refactors a bit of the data manipulation code in the handlers into individually testable utils.
This adds tests for the BookstoreVersionHandler.
There are a lot of issues that became obvious as I wrote these tests & helper utils. I will create separate issues for them, but I wanted to list them here. 
1. We should move BookstoreVersionHandler outside of the `handlers.py` module, into it's own module.
2. We could simplify the code without much work. But, the response is being used for validation by front-ends (e.g., nteract_on_jupyter), and so we will need to make sure that this works for them as well. 
Specifically, this would involve removing the `"bookstore": True` bit in the response from the BookstoreVersionHandler
3. Our tests are not all correctly awaiting the asynchronous …

Add test VersionHandler; Update Version Handler's API

---

bookstore/publish.py
bookstore/tests/test_publish.py
docs/source/bookstore_api.yaml
docs/source/reference/publish.rst

This takes some of the lessons from #139 and applies them to the publish module. 
Most notably it takes as much logic as possible out of the `_publish` method, making it only about speaking to s3 and nothing else.
Also, this moves a lot of the s3 string creation into the base `put` method & simplifies some of the logic that was happening in `prepare_response`.
This needed to build on #140 (since it changed the docstring), so if this is merged, that can be closed.

Publish refactor

---

bookstore/clone.py
bookstore/tests/test_clone.py

This addresses #145 for now. However it does not clarify why the issue arose in the first place.
It is likely that this results in a slightly lower coverage report. 
But, it has some advantages:
1. makes the tests slightly cleaner (since we no longer need to make a class to handle the asynchronous read) 
2. simplifies the API for build_content_model as we now can pass in a string rather than a dict with unused additional fields

Move async content reading inside s3 client context manager

---

bookstore/clone.html
bookstore/clone.py
bookstore/tests/test_clone.py

As part of the fs cloning handler, it requires changing how the clone.html template works. This makes it easier to construct a template that works for both handlers.
Main two changes are to move common behaviour to the backend, specifically:
1. creating the post model
2. creating the description of the source file

Update clone handler template

---

bookstore/bookstore_config.py
bookstore/clone.py
bookstore/tests/test_clone.py
docs/source/reference/clone.rst

This creates the utility that will be shared between the fs cloning handler & the fs cloning api handler:
- checks the behaviour of the basedir 
- ensures relpath exists 
- ensures relpath does escape out of the basedir

Validate relpath util

---

docs/source/bookstore_api.yaml

This adds REST API documentation for the new fs-clone endpoint.

Add REST docs for file system cloning endpoint

---

ci/integration.js
ci/jupyter.js

As I was working on the fs cloning API handler, I realized that we didn't have an integration test for the s3 cloning API handler.
We will need to cleanup the files created by the the cloning APIs, because otherwise we'll create a new file with a new name with each POST request. 
- Adds integration test for the POST handler (checks for the successful match between the published file (on s3), the cloned file (on disk) and the source content) 
- Updates the names to be more specifically about s3 cloning. 
- This also adds a cleanup to the integration tests & cleans up the side-effect notebooks.

Add s3clone integration test

---

bookstore/clone.py
bookstore/tests/test_clone.py
bookstore/tests/test_files/EmptyNotebook.ipynb
bookstore/utils.py
docs/source/reference/clone.rst

This adds the handler needed to get file system cloning to work. 
I will create a separate PR just for adding the handler to the routes and testing the routes. 
**NB**: This is a bit of a bigger PR, but I didn't want to submit a PR for functionality without tests for that functionality.

Fs cloning api handler

---

bookstore/handlers.py
bookstore/tests/test_handlers.py
docs/source/bookstore_api.yaml

This builds on #163 (and so should be reviewed in contrast to it rather than in its entirety).
This enables end-to-end testing of the full file system cloning experience.

Fs cloning api route

---

bookstore/archive.py
bookstore/tests/__init__.py
bookstore/tests/test_clone.py
ci/integration.js
ci/jupyter.js
ci/jupyter_notebook_config.py

This adds integration tests for file system cloning and is based on #162 and #164.
It also required addressing some minor inconsistencies I was discovering when I attempted to try our integration tests with a genuinely empty notebook.
These have to do with how the notebook stores cell `source` values in memory vs. on disk. Because we were using `json.dumps()` to get our to-disk content, we were not always writing out the appropriate information that was being passed through. This was most obvious in the case of an empty source `[]` which was being written to s3 as `''`. 
Using `nbformat.writes` and `nbformat.from_dict` alleviates the issue.

Add fsclone integration test & format improvements

---

bookstore/clone.html
bookstore/clone.py
bookstore/tests/test_clone.py

Currently by creating the entire the entire domain name, our way of constructing urls is not compatible with a bunch of proxy setups. 
Because we're not changing domain/origin with our links we can just use paths to define our redirect location and our api endpoint for the POST.
This switches us to use that logic.
As I went through making that change I discovered that our tests were not actually testing appropriately for the way that `base_url` and `default_url` on the Jupyter server work. 
Because our tests would break when I switched us to using paths, I added the logic needed to match the behaviour expected by the Jupyter server & the Tornado application. 
This primarily consisted of removing any cases where `self.base_url` did not begin and end with "/".  That required
- adding a …

Use paths not fully qualified domain names within bookstore

---

RELEASING.md
bookstore/clone.py
bookstore/tests/test_clone.py
docs/source/bookstore_api.yaml

This adds the ability to clone an old version from a versioned s3 bucket. 
Addresses #172 
Unfortunately we cannot test for this functionality in our minio based integration tests. This is because minio does not support versioned buckets:
see https://github.com/minio/minio/pull/6494 for the latest efforts to implement ending in a decision to not do so and https://github.com/minio/minio/issues/1309 for some of the original discussion around it.
This pulls out functionality around creating the kwargs to send to S3 so that we can test that logic independently.
This also updates the API docs.
@MSeal @captainsafia I added you as reviewers per your request earlier today at the team meeting.

S3 versioned cloning
